name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: check xcode
      run: ls -lah /Applications
    - name: build
      run: ./archive.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    - name: 'Store Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: WebViewScreenSaver.saver
        path: WebViewScreenSaver.saver.zip
